# Generated by Django 5.1.3 on 2024-11-20 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_house'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='current_money',
            field=models.IntegerField(default=50),
        ),
    ]
