# Generated by Django 5.1.3 on 2024-11-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_game_current_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
