# Generated by Django 5.1.3 on 2024-11-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_job_work_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='cooked_food',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='visited_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='visited_restaurant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
