# Generated by Django 5.1.3 on 2024-11-21 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_cooked_food_game_visited_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='play_count',
            field=models.IntegerField(default=0),
        ),
    ]
