# Generated by Django 5.1.3 on 2024-11-21 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0007_game_play_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='region',
            field=models.CharField(default='경상북도 청송군', max_length=255),
        ),
    ]
