# Generated by Django 5.1.3 on 2024-11-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_image',
            field=models.CharField(default='img/홈페이지일러.png', max_length=100),
        ),
    ]
