# Generated by Django 5.0.3 on 2024-11-20 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_customuser_profile_image_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.CharField(default='img/default_profile.png', max_length=100),
        ),
    ]
